"""Reporter: push the branch, open the pull request, notify the developer, record the run.

The reporter is a code step, not an agent. It runs after the review gate and
does its work in a fixed order with the tools called by code:

    1. notify and record a blocked outcome, without pushing, if the gate did not approve
    2. find the GitHub repository from the target's origin remote
    3. push the branch with git_push (protected branches are refused by the server)
    4. reuse an open pull request for the branch if one exists, otherwise open one
    5. notify_user with the outcome and the link
    6. write one JSON record of the run under the records folder

The pull request body is a template filled by code from the spec, the tests
added, the review summary and the non-blocking findings. The model is called
exactly once, to write a short paragraph describing the change for a human
skimming the pull request; if that call fails the template ships without it.
Every step records what completed, so a failure part way leaves an honest
record and a rerun can continue without repeating the push.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from pipeline.reviewer import describe_findings
from pipeline.tooling import call_tool, scrub_secrets

# Characters of diff given to the model for its paragraph; enough to see the change, not enough to flood the context.
DIFF_LIMIT = 3000
# Characters of a tool's output kept in the record when a step fails.
ERROR_LIMIT = 1000
# What the reporter records as the run's outcome.
READY, BLOCKED = "ready_to_review", "blocked"


def pull_request_title(task):
    """Return the pull request title in the same form as the branch's commit: "<type>: <short description>"."""
    return f"{task['type']}: {task['short_description'].replace('-', ' ')}"


def pull_request_body(task, review, paragraph, run_id):
    """Return the pull request body, templated from the task and the review, with the model's paragraph on top."""
    tests = "\n".join(f"- `{path}`" for path in task.get("tests", {})) or "- none"
    non_blocking = describe_findings(review.get("non_blocking_findings", [])) or "- none"
    test_record = review.get("test_record", {})
    scan = review.get("scan", {})
    return (
        f"## Summary\n\n{paragraph or '_No description was generated for this change._'}\n\n"
        f"## Request\n\n{task['spec']}\n\n"
        f"## Tests added\n\n{tests}\n\n"
        f"## Review\n\n{review.get('summary') or '_No review summary._'}\n\n"
        f"### Non-blocking findings\n\n{non_blocking}\n\n"
        f"## Checks\n\n"
        f"- Tests: {'passed' if test_record.get('passed') else 'failed'} ({test_record.get('summary', '')})\n"
        f"- Security scan: {'nothing blocking' if not scan.get('blocking') else 'blocking'}, "
        f"{len(scan.get('non_blocking_code_findings', []))} non-blocking code finding(s)\n\n"
        f"---\n_Run `{run_id}`, generated by the agentic pipeline. Nothing is merged automatically._\n"
    )


def parse_pull_request(text):
    """Return {"number", "url"} from a GitHub tool result, which is JSON for one pull request or a list of them, or None."""
    try:
        data = json.loads(text)
    except (TypeError, ValueError):
        return None
    # list_pull_requests returns a list; the first open one for the head is the one to reuse.
    if isinstance(data, list):
        data = data[0] if data else None
    if not isinstance(data, dict):
        return None
    url = data.get("html_url") or data.get("url")
    number = data.get("number")
    # The server's reply to create_pull_request carries the URL but not always a number field; the URL ends in it.
    if number is None and url:
        match = re.search(r"/pull/(\d+)", url)
        number = int(match.group(1)) if match else None
    return {"number": number, "url": url} if number is not None or url else None


async def describe_change(model, task, review, log):
    """Ask the model for one short paragraph describing the change for a human; return "" if that fails."""
    try:
        response = await model.ainvoke([
            SystemMessage(
                "Write one short paragraph, three sentences at most, for the summary of a pull request. "
                "Say what changed and why, in plain language for a colleague skimming the pull request. "
                "No headings, no lists, no code."
            ),
            HumanMessage(f"Request:\n{task['spec']}\n\nDiff:\n{review.get('diff', '')[:DIFF_LIMIT]}"),
        ])
        return str(response.content).strip()
    # The paragraph is a nicety; a model failure must not stop the pull request from being opened.
    except Exception as error:
        log(f"[reporter] the model could not describe the change: {scrub_secrets(error)[:200]}")
        return ""


async def report(repo_path, all_tools, model, task, branch, review, run_id, settings, log=print):
    """Push, open the pull request, notify and record, in that order, and return the run record."""
    tools_by_name = {tool.name: tool for tool in all_tools}

    async def dev_tools(name, **arguments):
        """Call a dev tools server tool and parse its JSON result."""
        return json.loads(await call_tool(tools_by_name, name, arguments))

    record = {
        "run_id": run_id,
        "started": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "task": {key: task.get(key) for key in ("type", "short_description", "spec")},
        "test_files": list(task.get("tests", {})),
        "branch": branch,
        "review": {
            "approved": review.get("approved"),
            "summary": review.get("summary", ""),
            "blocking_findings": review.get("blocking_findings", []),
            "non_blocking_findings": review.get("non_blocking_findings", []),
        },
        # Each step flips to a value once it completed, so a partial failure is visible in the record.
        "steps": {"pushed": False, "pull_request": None, "notified": False, "description_generated": False},
        "repository": None,
        "outcome": None,
        "error": None,
    }

    async def finish(outcome, summary, link="", error=None):
        """Notify the developer, complete the record, write it, and return it."""
        record["outcome"] = outcome
        record["error"] = scrub_secrets(error)[:ERROR_LIMIT] if error else None
        try:
            await dev_tools("notify_user", outcome=outcome, summary=summary, link=link)
            record["steps"]["notified"] = True
        # A failed notification is recorded but does not hide the outcome that was reached.
        except Exception as notify_error:
            log(f"[reporter] notification failed: {scrub_secrets(notify_error)[:200]}")
        record["finished"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        records_path = Path(settings["records_path"])
        records_path.mkdir(parents=True, exist_ok=True)
        (records_path / f"{run_id}.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
        log(f"[reporter] {outcome}: {summary}")
        return record

    # 1. A change the gate did not approve is reported, not pushed.
    if not review.get("approved"):
        findings = describe_findings(review.get("blocking_findings", []))
        return await finish(BLOCKED, f"{branch} was not approved by the review gate:\n{findings}")

    # 2. The repository comes from the target's origin remote, unless the settings override it.
    if settings.get("repository"):
        owner, repo = settings["repository"].split("/", 1)
    else:
        remote = await dev_tools("remote_repository")
        if remote.get("error"):
            return await finish(BLOCKED, f"{branch} could not be reported: {remote['error']}", error=remote["error"])
        owner, repo = remote["owner"], remote["repo"]
    record["repository"] = f"{owner}/{repo}"

    # 3. The push goes through the dev tools server, which refuses protected branches whatever is asked.
    push = await dev_tools("git_push")
    if not push.get("pushed"):
        error = push.get("error") or push.get("output", "")
        return await finish(BLOCKED, f"{branch} could not be pushed: {scrub_secrets(error)[:300]}", error=error)
    record["steps"]["pushed"] = True
    log(f"[reporter] pushed {branch}")

    # 4. Reuse an open pull request for this branch, so a rerun does not open a second one.
    try:
        existing = parse_pull_request(await call_tool(
            tools_by_name, "list_pull_requests", {"owner": owner, "repo": repo, "state": "open", "head": f"{owner}:{branch}"}
        ))
    except Exception as error:
        return await finish(BLOCKED, f"{branch} was pushed but GitHub could not be queried: {scrub_secrets(error)[:300]}", error=str(error))
    if existing:
        log(f"[reporter] reusing open pull request {existing['url']}")
        pull_request = existing
    else:
        paragraph = await describe_change(model, task, review, log)
        record["steps"]["description_generated"] = bool(paragraph)
        body = pull_request_body(task, review, paragraph, run_id)
        # Kept in the record so the body can be read later without asking GitHub for it.
        record["pull_request_body"] = body
        try:
            created = await call_tool(tools_by_name, "create_pull_request", {
                "owner": owner, "repo": repo, "title": pull_request_title(task),
                "head": branch, "base": settings["base_branch"], "body": body,
            })
        except Exception as error:
            return await finish(BLOCKED, f"{branch} was pushed but the pull request could not be opened: {scrub_secrets(error)[:300]}", error=str(error))
        pull_request = parse_pull_request(created)
        if pull_request is None:
            return await finish(BLOCKED, f"{branch} was pushed but GitHub's reply could not be read", error=created)
        log(f"[reporter] opened pull request {pull_request['url']}")
    record["steps"]["pull_request"] = pull_request

    # 5 and 6. Notify with the link and write the record.
    return await finish(READY, f"{pull_request_title(task)} ({branch})", link=pull_request["url"] or "")
